#!/bin/sh
#
# @name Griffin
#
# @type Quadrotor x
# @class Copter
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF == yes ]
then
	param set BAT_N_CELLS 6

	param set MIS_TAKEOFF_ALT 2.5
	
	param set MC_ROLL_P 5.451
	param set MC_ROLLRATE_P 0.3508
	param set MC_ROLLRATE_I 2.5755
	param set MC_ROLLRATE_D 0.0117
	param set MC_ROLLRATE_FF 0.0
	param set MC_ROLLRATE_MAX 120.0
	param set MC_ACRO_R_MAX 120.0
	
	param set MC_PITCH_P 5.451
	param set MC_PITCHRATE_P 0.3508
	param set MC_PITCHRATE_I 2.5755
	param set MC_PITCHRATE_D 0.0117
	param set MC_PITCHRATE_FF 0.0
	param set MC_PITCHRATE_MAX 120.0
	param set MC_ACRO_P_MAX 120.0
	
	param set MC_YAW_P 2.75
	param set MC_YAW_FF 0.0
	param set MC_YAWRATE_P 0.5829
	param set MC_YAWRATE_I 1.3558 
	param set MC_YAWRATE_D 0.0170
	param set MC_YAWRATE_FF 0.0
	param set MC_YAWRATE_MAX 45.0
	param set MC_YAWRAUTO_MAX 45.0
	param set MC_ACRO_Y_MAX 45.0
	param set MPC_MAN_Y_MAX 45.0
	
	param set MPC_TILTMAX_AIR 30.0
	param set MPC_MAN_TILT_MAX 30.0
	
	param set MPC_XY_P 0.8
	param set MPC_XY_VEL_P 0.0870
	param set MPC_XY_VEL_I 0.1201
	param set MPC_XY_VEL_D 0.0
	
	param set MPC_Z_P 1.7383
	param set MPC_Z_VEL_P 0.1729
	param set MPC_Z_VEL_I 0.3284
	param set MPC_Z_VEL_D 0

	param set PWM_MAX 1670
	
	param set MPC_THR_HOVER 0.3515625
	param set MPC_THR_MAX 1.0
	param set MPC_THR_MIN 0.0
fi

set MIXER quad_x