#!/bin/sh
#
# @name SLADe
#
# @type Quadrotor +
# @class Copter
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF == yes ]
then
	param set BAT_N_CELLS 6

	param set MIS_TAKEOFF_ALT 2.5
	
	param set MC_ROLL_P 9.1159
	param set MC_ROLLRATE_P 0.4205
	param set MC_ROLLRATE_I 1.6171
	param set MC_ROLLRATE_D 0.0259
	param set MC_ROLLRATE_FF 0.0
	
	param set MC_PITCH_P 9.1159
	param set MC_PITCHRATE_P 0.4205
	param set MC_PITCHRATE_I 1.6171
	param set MC_PITCHRATE_D 0.0259
	param set MC_PITCHRATE_FF 0.0
	
	param set MC_YAW_P 9.7266
	param set MC_YAW_FF 0.0
	param set MC_YAWRATE_P 20.5968
	param set MC_YAWRATE_I 79.2185
	param set MC_YAWRATE_D 1.2675
	param set MC_YAWRATE_FF 0.0
	
	param set MPC_XY_P 0.3
	param set MPC_XY_VEL_P 0.068
	param set MPC_XY_VEL_I 0.0068
	param set MPC_XY_VEL_D 0.0
	
	param set MPC_Z_P 0.3
	param set MPC_Z_VEL_P 0.068
	param set MPC_Z_VEL_I 0.0068
	param set MPC_Z_VEL_D 0
	
	param set MPC_THR_HOVER 0.5
fi

set MIXER quad_+